language: ruby
sudo: required
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m`
  - sudo mv docker-compose-`uname -s`-`uname -m` /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
install:
  - docker-compose build
script:
  - docker-compose run web rspec
