language: ruby
sudo: required
services:
  - docker

before_install:
  - sudo apt-get purge lxc-docker
  - sudo apt-get install docker-engine
install:
  - docker -v
  - docker build -t flowerpot/travisdockerexample .
script:
  - docker-compose run web rake
